version: '3.8'

services:
  db:
    container_name: mysql-5_7
    image: mysql:5.7.41
    platform: linux/amd64
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Tokyo
    # logファイルの生成と閲覧のために権限付与
    user: 1000:1000

volumes:
  db-store: